site_name: My Docs


# Repository
repo_name: chem
repo_url: https://github.com/hhlans/BLOG


theme:
    name: material
nav:
    - 主页: index.md
    - fu:
        - a: a.md

plugins:
  - search:
      lang: en