site_name: My Docs


# Repository
repo_name: chem
repo_url: https://github.com/hhlans/BLOG


theme:
  name: material
#  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
nav:
    - 主页:
          - zhuye:
            - zhuye: index.md
    - fu:
        - a: a.md

plugins:
  - search:
      lang: en