site_name: 化工博客


# Repository
repo_name: chem
repo_url: https://github.com/hhlans/BLOG


theme:
  name: material
#  custom_dir: material/overrides
  favicon: 'favicon.ico'
  logo: 'favicon.ico'
  features:
    palette:
      scheme: default
      primary: indigo
      accent: indigo

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
    - 主页:
          - 概述: index.md
    - 博客搭建模版 :
        - 颜色: ctc.md

plugins:
  - search:
      lang: en

